### ISSUE TITLE
Cannot read property 'find' of null

### ISSUE THREAD

**Issue by darkman242** [peterbaumert/ioBroker.unifi-protect#108]
Fehler beim Neustart des Adapters nach dem Hinzufügen von weiteren Kameras

Unifi Protect 1.21.2 (wegen unifi-cam-proxy)
js-controller: 4.0.21
node-js: 14.19.1

`<html>
<body>

unifi-protect.0 | 2022-04-06 17:04:26.741 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
unifi-protect.0 | 2022-04-06 17:04:26.732 | error | Cannot read property 'find' of null
unifi-protect.0 | 2022-04-06 17:04:26.732 | error | TypeError: Cannot read property 'find' of null at ProtectApi.getFullNameById (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:424:31) at ProtectUpdateEvents.motionEventHandler (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-update-events.js:365:77) at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-update-events.js:309:12) at WebSocket.emit (events.js:412:35) at WebSocket.emit (domain.js:475:12) at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/websocket.js:1137:20) at Receiver.emit (events.js:400:28) at Receiver.emit (domain.js:475:12) at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/receiver.js:513:14) at Receiver.getData (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/receiver.js:446:17)
unifi-protect.0 | 2022-04-06 17:04:26.729 | error | unhandled promise rejection: Cannot read property 'find' of null
unifi-protect.0 | 2022-04-06 17:04:26.728 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

**Comment by Xenon-s** [comment]
ich habe mir eine modifizierte Version gebaut um die Fehler zu finden und eine neue Version zu bauen ;) etwas Geduld werden wir aber alle brauchen ..

**Comment by peterbaumert** [comment]
> ich habe mir eine modifizierte Version gebaut um die Fehler zu finden und eine neue Version zu bauen ;) etwas Geduld werden wir aber alle brauchen ..
> 
> 
> 
> @Apollon77 zur Info

Willst du den adapter übernehmen oder soll ich ihn irgendjemand übertragen der mehr zeit hat?

**Comment by Xenon-s** [comment]
PR wartet auf dich ;)
