### ISSUE TITLE
Adapter loop und Neustart

### ISSUE THREAD

**Issue by meanwhile28** [peterbaumert/ioBroker.unifi-protect#99]
Adapter wird neugestartet und looped bei Erkennung von Bewegungen die erkannt werden.

**To Reproduce**  
Bewegung auslösen

**Expected behavior**  
Snapshot wird erstellt und gespeichert.

**Logfiles**  
unifi-protect.0 | 2022-02-21 18:01:25.377 | info | 172.16.10.52: Connected to the UniFi realtime update events API.
-- | -- | -- | --
unifi-protect.0 | 2022-02-21 18:01:25.344 | info | 172.16.10.52: Connected to the Protect controller API (address: 172.16.10.52 mac: 784558DECB59).
unifi-protect.0 | 2022-02-21 18:01:24.267 | info | starting. Version 0.0.12 in /opt/iobroker/node_modules/iobroker.unifi-protect, node: v12.22.8, js-controller: 3.3.22
host.e88d810f7b56 | 2022-02-21 18:01:22.203 | info | instance system.adapter.unifi-protect.0 started with pid 17052
host.e88d810f7b56 | 2022-02-21 18:00:52.148 | info | Restart adapter system.adapter.unifi-protect.0 because enabled
host.e88d810f7b56 | 2022-02-21 18:00:52.147 | error | instance system.adapter.unifi-protect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.e88d810f7b56 | 2022-02-21 18:00:52.146 | error | Caught by controller[1]: at Receiver.getData (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/receiver.js:446:17)
host.e88d810f7b56 | 2022-02-21 18:00:52.146 | error | Caught by controller[1]: at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/receiver.js:513:14)
host.e88d810f7b56 | 2022-02-21 18:00:52.145 | error | Caught by controller[1]: at Receiver.EventEmitter.emit (domain.js:483:12)
host.e88d810f7b56 | 2022-02-21 18:00:52.145 | error | Caught by controller[1]: at Receiver.emit (events.js:314:20)
host.e88d810f7b56 | 2022-02-21 18:00:52.144 | error | Caught by controller[1]: at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/websocket.js:1137:20)
host.e88d810f7b56 | 2022-02-21 18:00:52.144 | error | Caught by controller[1]: at WebSocket.EventEmitter.emit (domain.js:483:12)
host.e88d810f7b56 | 2022-02-21 18:00:52.144 | error | Caught by controller[1]: at WebSocket.emit (events.js:326:22)
host.e88d810f7b56 | 2022-02-21 18:00:52.143 | error | Caught by controller[1]: at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-update-events.js:309:12)
host.e88d810f7b56 | 2022-02-21 18:00:52.143 | error | Caught by controller[1]: at ProtectUpdateEvents.motionEventHandler (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-update-events.js:365:77)
host.e88d810f7b56 | 2022-02-21 18:00:52.142 | error | Caught by controller[1]: at ProtectApi.getFullNameById (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:424:31)
host.e88d810f7b56 | 2022-02-21 18:00:52.142 | error | Caught by controller[1]: TypeError: Cannot read property 'find' of null
host.e88d810f7b56 | 2022-02-21 18:00:52.141 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
unifi-protect.0 | 2022-02-21 18:00:51.452 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
unifi-protect.0 | 2022-02-21 18:00:51.448 | info | terminating
unifi-protect.0 | 2022-02-21 18:00:51.446 | info | cleaned everything up...
unifi-protect.0 | 2022-02-21 18:00:51.407 | error | Cannot read property 'find' of null
unifi-protect.0 | 2022-02-21 18:00:51.406 | error | TypeError: Cannot read property 'find' of null at ProtectApi.getFullNameById (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:424:31) at ProtectUpdateEvents.motionEventHandler (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-update-events.js:365:77) at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-update-events.js:309:12) at WebSocket.emit (events.js:326:22) at WebSocket.EventEmitter.emit (domain.js:483:12) at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/websocket.js:1137:20) at Receiver.emit (events.js:314:20) at Receiver.EventEmitter.emit (domain.js:483:12) at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/receiver.js:513:14) at Receiver.getData (/opt/iobroker/node_modules/iobroker.unifi-protect/node_modules/ws/lib/receiver.js:446:17)
unifi-protect.0 | 2022-02-21 18:00:51.389 | error | unhandled promise rejection: Cannot read property 'find' of null
unifi-protect.0 | 2022-02-21 18:00:51.387 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Versions:**  
 - Adapter version: 0.0.12
 - JS-Controller version: 3.3.22
 - Node version: v12.22.8
 - Operating system: docker container on raspi

**Comment by fladdie** [comment]
Ich habe das gleiche Problem

**Comment by Xenon-s** [comment]
@peterbaumert I have the same problem. The adapter is no longer usable and does not get past a restart loop. 

Unifi protect version :1.21.3
JS Controller: 4.0.21
NodeJS : 14.19.1

**Comment by luxi-asphericon** [comment]
Hi, muss mich leider anschließen.
Hab mir nun extra ne Unifi Chime zugelegt da iobroker nun nicht mehr "klingelt"
Ich nutze 
UniFi OS UDM Pro 2.5.17
Unifi Protect 2.2.11
Unifi Protect Adapter v0.0.13
Node.js: v16.19.0

**Comment by luxi-asphericon** [comment]
Ich hab mal node.js auf 18.x hochgezogen. Jetzt scheint es wieder stabil zu laufen.
@peterbaumert Prima Arbeit vielen Dank
